config/routes.rb
Rails.application.routes.draw do
  # 制限有りはdevise_for :users,skip: [:passwords], controllers: {
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get "/about"=>"homes#about"
    resources :users, except: [:new, :create] do
      get "unsubscribe"=>"users#unsubscribe"
      patch "withdrawal"=>"users#withdrawal"
    end
    resources :recipes do
      resources :reviews, only: [:index, :create]
      resources :reports, only: [:new, :create]#暫定追加、実証時削除
    end
  end
  # 制限有りはdevise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  devise_for :admin ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root to: 'homes#top'
    resources :user, only: [:index, :edit, :update, :destroy]
    #以下adminはすべてこの中に
  end
end

# test_user
# test@mail
# 111111

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!--顧客側ログイン-->
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto">

            <li class="nav-item mb-1 mb-lg-0">
              <%= link_to user_path(id: current_user.id), class: 'nav-link text-dark btn me-2' do %>
                <i class="fas fa-home"></i><%= " マイページ" %>
              <% end %>
            </li>

            <li class="nav-item mb-1 mb-lg-0">
              <%= link_to users_path, class: 'nav-link text-dark btn me-2' do %>
                <i class="fas fa-book"></i><%= " ユーザー一覧" %>
              <% end %>
            </li>

            <li class="nav-item mb-1 mb-lg-0">
              <%= link_to recipes_path, class: 'nav-link text-dark btn me-2' do %>
                <i class="fas fa-book"></i><%= " レシピ一覧" %>
              <% end %>
            </li>

            <li class="nav-item mb-1 mb-lg-0">
              <%= link_to root_path, class: 'nav-link text-dark btn me-2' do %>
                <i class="fas fa-pencil-alt"></i><%= "レシピを書く" %>
              <% end %>
            </li>

            <li class="nav-item mb-1 mb-lg-0">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark btn me-2' do %>
                <i class="fas fa-sign-out-alt"></i><%= " ログアウト" %>
              <% end %>
            </li>
          </ul>
        </div>
      <% elsif admin_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto">

            <li class="nav-item mb-1 mb-lg-0">
              <%= link_to recipes_path, class: 'nav-link text-dark btn me-2' do %>
                <i class="fas fa-book"></i><%= " レシピ一覧" %>
              <% end %>
            </li>

            <li class="nav-item  mb-1 mb-lg-0">
              <%= link_to root_path, class: 'nav-link text-dark btn me-2' do %>
                <i class="fas fa-users"></i><%= " 会員一覧" %>
              <% end %>
            </li>

            <li class="nav-item  mb-1 mb-lg-0">
              <%= link_to root_path, class: 'nav-link text-dark btn me-2' do %>
                <i class="fas fa-tags"></i><%= "タグ一覧" %>
              <% end %>
            </li>

            <li class="nav-item  mb-1 mb-lg-0">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark btn me-2' do %>
                <i class="fas fa-sign-out-alt"></i><%= " ログアウト" %>
              <% end %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto">

            <li class="nav-item mb-2 mb-lg-0">
              <%= link_to root_path, class: 'nav-link text-dark btn me-2' do %>
                <i class="far fa-clipboard"></i><%= " ガイド" %>
              <% end %>
            </li>

            <li class="nav-item  mb-2 mb-lg-0">
              <%= link_to recipes_path, class: 'nav-link text-dark btn me-2' do %>
                <i class="fas fa-book"></i><%= " レシピ一覧" %>
              <% end %>
            </li>

            <li class="nav-item  mb-2 mb-lg-0">
              <%= link_to new_user_registration_path, class: 'nav-link text-dark btn me-2' do %>
                <i class="fas fa-user-plus"></i><%= " 新規登録" %>
              <% end %>
            </li>

            <li class="nav-item  mb-2 mb-lg-0">
              <%= link_to new_user_session_path,  class: 'nav-link text-dark btn me-2' do %>
                <i class="fas fa-sign-in-alt"></i><%= " ログイン" %>
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestModel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <!--フラッシュメッセージの表示-->
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <i class="fas fa-check-circle"></i><%= notice %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <i class="fas fa-exclamation-triangle mr-2"></i><%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <!--< %= render 'layouts/footer' %>-->
  </body>
</html>